[project]
name = "my-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-identity>=1.25.3",
    "deltalake>=1.6.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.27.2",
    "pandas>=3.0.3",
    "pyarrow>=24.0.0",
    "pyodbc>=5.3.0",
    "requests>=2.34.2",
]
